org: absternator
app: aws-python-http-api-project
service: aws-python-http-api-project
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  httpApi:
    cors: true

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: post
